Первое ДЗ
Kate-Dem/DZ-HTML-CSS pull request #1
Opened 2024-06-22 00:01 UTC by Kate-Dem

2024-07-05 07:25 UTC, GitEsense requested changes
Давайте внесём некоторые корректировки, построим структуру чуть удобнее и расставим всё на места, чтобы дальше нам было сильно проще стилизовать

2024-07-05 07:25 UTC, GitEsense commented on 1- blog/index.html
> +</form>
Вот эта форма - она и есть "поиск", она находится у нас в header но после навигационного меню - надо бы перенести

2024-07-05 07:25 UTC, GitEsense commented on 1- blog/index.html
> +				<li>Мой блог</li>
"В" Мой блог - это логотип, он так же не относится к навигационному меню (как и форма), но является ссылкой, можем поставить перед навигацией

2024-07-05 07:25 UTC, GitEsense commented on 1- blog/index.html
> +				<li>Поиск</li>
Последний пункт лишний, а все элементы списка являются ссылками - всё-таки это навигация, а значит переходы, а значит ссылка ведущая куда-то (по умолчанию мы используем пустой хэш `#` )

2024-07-05 07:25 UTC, GitEsense commented on 1- blog/index.html
> +	<div>
Можно конечно дополнительно всё обернуть, но необходимости нет, по сути мы будем иметь структуру
```html
<html>
    <head>
    <body>
        <header>
        <main>
        <footer>
```

2024-07-05 07:25 UTC, GitEsense commented on 1- blog/index.html
> +			</p>
Можно оставить так, но потом стилизовать будет неудобно, хорошо бы сделать отдельный блок, объединения контента (div), затем вложить два параграфа внутрь, где первый будет - Автор, второй - профессия, тогда и получится структура - аватарка + описание
```html
<div>
    <img>
    <div>
          <p>
          <p>
```

2024-07-05 07:25 UTC, GitEsense commented on 1- blog/index.html
> +		<div>Все права защищены &#169; 2024</div>
Если у нас очевидно текстовый блок - то вместо блока объединения контента давайте использовать семантически верный - параграф (для текста), а вот если бы мы объединяли несколько блоков в один - тогда бы оно нам и пригодилось

2024-07-05 07:25 UTC, GitEsense commented on 2 форм/index.html
> +	</main>
Если мы в перспективе планируем позиционировать main как основной (белый фон и содержимое), то такая конструкция подойдёт, а если нет, тогда хорошо бы заголовок и параграф вложить в форму (как часть блока), а для выделения воспользоваться div (или не делать), т.к. у нас блочное поведение и у заголовка, и у параграфа, поэтому ничего критичного, однако, когда мы будем работать с флексами (уже ближе к завершению курса) - будет удобнее разделить на headling и fields

2024-07-05 07:25 UTC, GitEsense commented on 2 форм/index.html
> +			<p>Моя компания</p>
а "Моя компания" - это тоже классический инпут, однако, на макете показано состояние "фокус", т.е. данный инпут будет ровно такой же как и остальные, но при навешивании стилей мы будем использовать псевдокласс `focus`, чтобы настроить изменение стиля инпута при его "выборе" и он будет как раз вот таким, как реализован "Моя компания" (тут уже заполнено значение и введен текст `Моя компания`), классический placeholder же будет `Компания`

2024-07-05 07:25 UTC, GitEsense commented on 2 форм/index.html
> +				<input type="checkbox" name="agree" id="agree">
А вот тут лучше поменять инпут и лейбл местами, т.к. checkbox у нас идёт перед текстом.
в лейбл же можно не выделять ссылку span'ом, ведь ссылка имеет своё "оформление", а обычный текст будет стилизоваться за счёт лейбла

2024-07-06 00:18 UTC, Kate-Dem commented
Благодарю за подробное объяснение всех ошибок!

2024-07-09 08:36 UTC, GitEsense approved these changes

2024-07-09 08:36 UTC, GitEsense commented on 1- blog/index.html
> +		</div>
Вот тут мы так же можем объединить в `div` - т.к. это один блок контента, в котором есть
1. Картинка (аватарка)
2. Текстовое описание, объединённое контентным блоком
Тогда получим 
```html
<div>
    <div> /* Этот div можно было бы не использовать, но иногда обернуть картинку не будет лишним */
          <img>
     </div>
      <div>
            <p>...</p>
            <p>...</p>
     </div>
</div>
```

2024-07-09 08:36 UTC, GitEsense commented on 1- blog/index.html
> +		<div>Все права защищены &#169; 2024</div>
Всё-таки лучше давайте сделаем <p>

2024-07-09 08:36 UTC, GitEsense commented on 2 форм/index.html
> +
Раз мы выделяем заголовок, то может удобнее будет (настаивать не буду) на следующем
```html
<form>
    <header> /* Можно было бы оставить div, но так мы семантически выделили, что это заголовок формы */
        <h1>Регистрация</h1>
        <p>Уже есть аккаунт?<span><a href="#">Войти</a></span> </p>
    </header>
    <main> /* мог бы быть так же div, но мы выделили "тело" */
        <div>
            <label for="company"></label>
            <input type="text" id="company" name="company" placeholder="Компания" required>
        </div>
        <div>
            <div>
                <label for="name"></label>
                <input type="text" id="name" name="name" placeholder="Имя" required>
            </div>
            <div>
                <label for="surname"></label>
                <input type="text" id="surname" name="surname" placeholder="Фамилия" required>
            </div>
        </div>
        <div>
            <label for="email"></label>
            <input type="email" id="email" name="email" placeholder="E-mail">
        </div>
        <button>Зарегистрироваться</button>
        <div>
            <input type="checkbox" name="agree" id="agree">
            <label for="agree">Я прочитал и принимаю <a href="#">Условия использования</a></label>
        </div>
</form>
```
В данной вариации мы выделили инпуты с лейблами в свои "блоки", чтобы они были "объедены" (например лейбл станет иконкой когда-нибудь и так будет легче их стилизовать), но для данной реализации достаточно будет "упрощённого" формата

```html
<form>
    <header> /* Можно было бы оставить div, но так мы семантически выделили, что это заголовок формы */
        <h1>Регистрация</h1>
        <p>Уже есть аккаунт?<span><a href="#">Войти</a></span> </p>
    </header>
    <main> /* мог бы быть так же div, но мы выделили "тело" */
        <input type="text" id="company" name="company" placeholder="Компания" required>
        <div>
            <input type="text" id="name" name="name" placeholder="Имя" required>
            <input type="text" id="surname" name="surname" placeholder="Фамилия" required>
        </div>
        <input type="email" id="email" name="email" placeholder="E-mail">
        <button>Зарегистрироваться</button>
        <div>
            <input type="checkbox" name="agree" id="agree">
            <label for="agree">Я прочитал и принимаю <a href="#">Условия использования</a></label>
        </div>
</form>
```

2024-07-09 21:05 UTC, Kate-Dem commented
Спасибо, все замечания понятны. Я внесла изменения.

2024-07-09 21:31 UTC, merged